version: "3"

services:

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: DOCKER://:9091,HOST://:9092
      KAFKA_ADVERTISED_LISTENERS: DOCKER://kafka:9091,HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: DOCKER:PLAINTEXT,HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER

  kafdrop:
    image: obsidiandynamics/kafdrop:3.28.0-SNAPSHOT
    container_name: kafdrop
    depends_on:
      - kafka
    restart: always
    ports:
      - "19000:9000"                                              # KAFDROP   http://localhost:9000
    environment:
      KAFKA_BROKERCONNECT: "kafka:9091"
      SERVER_PORT: "9000"
      JVM_OPTS: "-Xms32M -Xmx164M"
      SERVER_SERVLET_CONTEXTPATH: "/"
